version: "3.7"
services:
  database:
    image: postgres:12.7
    restart: always
    environment:
      POSTGRES_DB: ticketbookingdb
      POSTGRES_USER: ticketbookinguser
      POSTGRES_PASSWORD: AToughPassword!
    ports:
      - "5432:5432"
    volumes:
      - data:/var/lib/postgresql/data
  server:
    build:
      context: .
      dockerfile: Dockerfile
    env_file: .env
    depends_on:
      - database
    networks:
      - default
    ports:
      - "8080:8080"
volumes:
  data: